# Generated by Django 5.2.16 on 2026-07-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_machinegroup_rustdeskpeer_machine_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rustdesdevice",
            options={
                "ordering": ("-rid",),
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
            },
        ),
        migrations.AlterModelOptions(
            name="rustdeskpeer",
            options={
                "ordering": ("-username",),
                "verbose_name": "Peers",
                "verbose_name_plural": "Peers",
            },
        ),
        migrations.AlterModelOptions(
            name="rustdesktag",
            options={
                "ordering": ("-uid",),
                "verbose_name": "Tags",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.AlterModelOptions(
            name="rustdesktoken",
            options={
                "ordering": ("-username",),
                "verbose_name": "Token",
                "verbose_name_plural": "Tokens",
            },
        ),
        migrations.AlterModelOptions(
            name="sharelink",
            options={
                "ordering": ("-create_time",),
                "verbose_name": "Share link",
                "verbose_name_plural": "Share links",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "permissions": (
                    ("view_task", "Can see available tasks"),
                    ("change_task_status", "Can change the status of tasks"),
                    ("close_task", "Can remove a task by setting its status as closed"),
                ),
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AlterField(
            model_name="rustdesdevice",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Registered at"),
        ),
        migrations.AlterField(
            model_name="rustdesdevice",
            name="hostname",
            field=models.CharField(max_length=100, verbose_name="Hostname"),
        ),
        migrations.AlterField(
            model_name="rustdesdevice",
            name="memory",
            field=models.CharField(max_length=100, verbose_name="Memory"),
        ),
        migrations.AlterField(
            model_name="rustdesdevice",
            name="os",
            field=models.CharField(max_length=100, verbose_name="Operating system"),
        ),
        migrations.AlterField(
            model_name="rustdesdevice",
            name="rid",
            field=models.CharField(blank=True, max_length=60, verbose_name="Client ID"),
        ),
        migrations.AlterField(
            model_name="rustdesdevice",
            name="update_time",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="rustdesdevice",
            name="username",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="OS username"
            ),
        ),
        migrations.AlterField(
            model_name="rustdesdevice",
            name="version",
            field=models.CharField(max_length=100, verbose_name="Client version"),
        ),
        migrations.AlterField(
            model_name="rustdeskpeer",
            name="alias",
            field=models.CharField(max_length=30, verbose_name="Alias"),
        ),
        migrations.AlterField(
            model_name="rustdeskpeer",
            name="hostname",
            field=models.CharField(max_length=30, verbose_name="Computer name"),
        ),
        migrations.AlterField(
            model_name="rustdeskpeer",
            name="platform",
            field=models.CharField(max_length=30, verbose_name="Platform"),
        ),
        migrations.AlterField(
            model_name="rustdeskpeer",
            name="rhash",
            field=models.CharField(max_length=60, verbose_name="Device password hash"),
        ),
        migrations.AlterField(
            model_name="rustdeskpeer",
            name="rid",
            field=models.CharField(max_length=60, verbose_name="Client ID"),
        ),
        migrations.AlterField(
            model_name="rustdeskpeer",
            name="tags",
            field=models.CharField(max_length=30, verbose_name="Tags"),
        ),
        migrations.AlterField(
            model_name="rustdeskpeer",
            name="uid",
            field=models.CharField(max_length=16, verbose_name="User ID"),
        ),
        migrations.AlterField(
            model_name="rustdeskpeer",
            name="username",
            field=models.CharField(max_length=20, verbose_name="OS username"),
        ),
        migrations.AlterField(
            model_name="rustdesktag",
            name="tag_color",
            field=models.CharField(blank=True, max_length=60, verbose_name="Tag color"),
        ),
        migrations.AlterField(
            model_name="rustdesktag",
            name="tag_name",
            field=models.CharField(max_length=60, verbose_name="Tag name"),
        ),
        migrations.AlterField(
            model_name="rustdesktag",
            name="uid",
            field=models.CharField(max_length=16, verbose_name="Owner user ID"),
        ),
        migrations.AlterField(
            model_name="rustdesktoken",
            name="access_token",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="Access Token"
            ),
        ),
        migrations.AlterField(
            model_name="rustdesktoken",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Login time"),
        ),
        migrations.AlterField(
            model_name="rustdesktoken",
            name="uid",
            field=models.CharField(max_length=16, verbose_name="User ID"),
        ),
        migrations.AlterField(
            model_name="rustdesktoken",
            name="username",
            field=models.CharField(max_length=20, verbose_name="Username"),
        ),
        migrations.AlterField(
            model_name="rustdesktoken",
            name="uuid",
            field=models.CharField(max_length=60, verbose_name="UUID"),
        ),
        migrations.AlterField(
            model_name="sharelink",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="sharelink",
            name="is_expired",
            field=models.BooleanField(default=False, verbose_name="Expired"),
        ),
        migrations.AlterField(
            model_name="sharelink",
            name="is_used",
            field=models.BooleanField(default=False, verbose_name="Used"),
        ),
        migrations.AlterField(
            model_name="sharelink",
            name="peers",
            field=models.CharField(max_length=20, verbose_name="Peer ID list"),
        ),
        migrations.AlterField(
            model_name="sharelink",
            name="shash",
            field=models.CharField(max_length=60, verbose_name="Link key"),
        ),
        migrations.AlterField(
            model_name="sharelink",
            name="uid",
            field=models.CharField(max_length=16, verbose_name="User ID"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="deviceInfo",
            field=models.TextField(blank=True, verbose_name="Login info"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="Administrator"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="username",
            field=models.CharField(max_length=50, unique=True, verbose_name="Username"),
        ),
    ]
