"""
Django settings for rustdesk_server_api project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
if "CSRF_TRUSTED_ORIGINS" in os.environ:
    CSRF_TRUSTED_ORIGINS = [os.environ["CSRF_TRUSTED_ORIGINS"]]
else:
    CSRF_TRUSTED_ORIGINS = ["http://127.0.0.1:21114"]
    SECURE_CROSS_ORIGIN_OPENER_POLICY = 'None'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Prefer SECRET_KEY from the environment; otherwise generate one once and
# persist it under db/ (a mounted volume in Docker) so sessions survive restarts.
SECRET_KEY = os.environ.get("SECRET_KEY", "")
if not SECRET_KEY:
    _key_file = BASE_DIR / 'db' / 'secret_key.txt'
    try:
        SECRET_KEY = _key_file.read_text().strip()
    except OSError:
        SECRET_KEY = ''
    if not SECRET_KEY:
        from django.core.management.utils import get_random_secret_key
        SECRET_KEY = get_random_secret_key()
        try:
            _key_file.parent.mkdir(parents=True, exist_ok=True)
            _key_file.write_text(SECRET_KEY)
        except OSError:
            pass  # read-only filesystem: key regenerates each start (sessions reset)
# ID server host (often same as relay); used by the web client
ID_SERVER = os.environ.get("ID_SERVER", '')
# SECURITY WARNING: don't run with debug turned on in production!
# Note: env vars are strings — "False" is truthy, so parse explicitly.
DEBUG = str(os.environ.get("DEBUG", "False")).lower() in ('true', '1', 'yes')
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
ALLOWED_HOSTS = ["*"]
AUTH_USER_MODEL = 'api.UserProfile'

ALLOW_REGISTRATION = os.environ.get("ALLOW_REGISTRATION", "True")
ALLOW_REGISTRATION = True if ALLOW_REGISTRATION.lower() == 'true' else False


# ========== Database (SQLite default; MySQL / PostgreSQL optional) ==========
DATABASE_TYPE = os.environ.get("DATABASE_TYPE", 'SQLITE')
MYSQL_DBNAME = os.environ.get("MYSQL_DBNAME", '-')
MYSQL_HOST = os.environ.get("MYSQL_HOST", '127.0.0.1')
MYSQL_USER = os.environ.get("MYSQL_USER", '-')
MYSQL_PASSWORD = os.environ.get("MYSQL_PASSWORD", '-')
MYSQL_PORT = os.environ.get("MYSQL_PORT", '3306')
POSTGRES_DBNAME = os.environ.get("POSTGRES_DBNAME", '-')
POSTGRES_HOST = os.environ.get("POSTGRES_HOST", '127.0.0.1')
POSTGRES_USER = os.environ.get("POSTGRES_USER", '-')
POSTGRES_PASSWORD = os.environ.get("POSTGRES_PASSWORD", '-')
POSTGRES_PORT = os.environ.get("POSTGRES_PORT", '5432')
# ========== End database ==========

LANGUAGE_CODE = os.environ.get("LANGUAGE_CODE", 'en')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'webui',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'rustdesk_server_api.middleware.NormalizeDoubleApiPrefixMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',  # CSRF disabled for legacy API POST
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rustdesk_server_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'api.util.settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'rustdesk_server_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db/db.sqlite3',
        # Longer busy timeout helps concurrent RustDesk clients (sysinfo/heartbeat) on SQLite.
        'OPTIONS': {
            'timeout': int(os.environ.get('SQLITE_BUSY_TIMEOUT', '30')),
        },
    }
}
if DATABASE_TYPE == 'MYSQL' and MYSQL_DBNAME != '-' and MYSQL_USER != '-' and MYSQL_PASSWORD != '-':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': MYSQL_DBNAME,
            'HOST': MYSQL_HOST,
            'USER': MYSQL_USER,
            'PASSWORD': MYSQL_PASSWORD,
            'PORT': MYSQL_PORT,
            'OPTIONS': {'charset': 'utf8'},
        }
    }
elif DATABASE_TYPE == 'POSTGRESQL' and POSTGRES_DBNAME != '-' and POSTGRES_USER != '-' and POSTGRES_PASSWORD != '-':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': POSTGRES_DBNAME,
            'HOST': POSTGRES_HOST,
            'USER': POSTGRES_USER,
            'PASSWORD': POSTGRES_PASSWORD,
            'PORT': POSTGRES_PORT,
        }
    }

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

# LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

# USE_TZ = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = 'static/'

if DEBUG:
    STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')

LANGUAGES = (
    ('en', 'English'),
    ('zh-hans', 'Chinese (Simplified)'),
)

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)
